[package]
name = "elide"
version = "2.0.3"
edition = "2021"
description = "I'mma beat Doom."
license = "MIT"
repository = "https://github.com/tunglamtrannguyen3-cmd/ELIDE"

[dependencies]
# Terminal handling
crossterm = "0.29"

# TUI rendering
ratatui = "0.30"

# Async runtime for non-blocking execution
tokio = { version = "1.53", features = ["full"] }

# Error handling
anyhow = "1.0"

# Direct Linux Kernel & POSIX interfaces
libc = "0.2"

# System call wrapper with Peak RAM tracking via getrusage
nix = { version = "0.31", features = ["process", "mman", "ptrace", "resource", "user"] }

# Linux eBPF kernel space program loader & Tokio integration
aya = "0.14"

unicode-width = "0.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
url = "2.5.8"

[profile.release]
opt-level = 3
lto = "fat"              # Full Link-Time Optimization
panic = "abort"          # Eliminates unwinding landing pads
codegen-units = 1

